### ISSUE TITLE
An error occurred while submitting

### ISSUE THREAD

**Issue by nikafighting** [Toloka/WSDMCup2023#1]
The answer.zip was generated and submitted by the following steps:
1.Write a results to a csv-file with comma separation having columns: image, left, top, right, bottom
2.Name this file answer.csv - this name is mandatory, otherwise the submission will not be processed
3.Zip answer.csv file
4.Submit archive at 'Participate' -> 'Submit' section 

But the pop-up window showed  "An unexpected error occurred.".

**Comment by nikafighting** [comment]
[answer.zip](https://github.com/Toloka/WSDMCup2023/files/10056593/answer.zip)

**Comment by denaxen** [comment]
Hi!
I have successfully submitted your archive without error.
Probably, if the file can't even be sent, the problem is in the "Method name" or "Method description" field which you write on the submission page above the "Submit" button. Try to reduce the number of symbols in these fields
